// Export all frame models
export * from './FrameBlazingSunIcon.model';
export * from './FrameBlueCrystalIcon.model';
export * from './FrameBlueFireIcon.model';
export * from './FrameDiamondIcon.model';
export * from './FrameFloralWreathIcon.model';
export * from './FrameGoldenFloralIcon.model';
export * from './FrameIcyWingsIcon.model';
export * from './FrameMagentaWingsIcon.model';
export * from './FrameNeonDiamondIcon.model';
export * from './FrameNeonPinkIcon.model';
export * from './FrameOrnateBronzeIcon.model';
export * from './FramePinkGemIcon.model';
export * from './FramePinkLaceIcon.model';
export * from './FramePurpleFloralIcon.model';
export * from './FrameRegalPurpleIcon.model';
export * from './FrameRoseHeartIcon.model';
export * from './FrameSilverBeadedIcon.model';
export * from './FrameSilverThornIcon.model';
